
type B {
  id: ID
  refC: C
  refD: D
}
type C {
  id: ID

}
type D {
  id: ID
  refY: Y
}
type E {
  id: ID
  refF: F
}
type F {
  id: ID
  refG: G
}
type G {
  id: ID
  refH: H
}
type H {
  id: ID
  refE: E
}

union Y = C | B

union X = D | B | A | C

type A {
  id: ID
  refB: X
}