
type B {
  id: ID
  refC: C
  refD1: D
  refD2: D
}
type C {
  id: ID

}
type D {
  id: ID
  refB: B
  refY: Y
}
type E {
  id: ID
  refF: F
}
type F {
  id: ID
  refG: G
}
#type G implements Z {
type G {
  id: ID
  refH: H
  #irefH: H
}
type H {
  id: ID
  refE: E
}

#interface Z {
#  id: ID
#  irefH: H
#}

union Y = B | C

union X = A | B | C | D

type A {
  id: ID
  refX: X
}