type A {
  id: ID
  refB: B
}

type B {
  id: ID
  refC: C
  refE1: E
  refE2: E
}

type C {
  id: ID
  refA: A
  refF: F
}

type D {
  id: ID
  refB: B
  refM: M
}

type E {
  id: ID
  refD: D
  refF: F
  refP1: P
  refP2: P
}

type F {
  id: ID
  refG: G
  refI: I
  refK: K
}

type G {
  id: ID
  refH: H
}

type H {
  id: ID
  refI1: I
  refI2: I
}

type I {
  id: ID
  refJ: J
  refG: G
}

type J {
  id: ID
  refJ: J
}

type K {
  id: ID
  refJ: J
  refL: L
}

type L {
  id: ID
  refK: K
}

type M {
  id: ID
  refP: P
}

type N {
  id: ID
  refM1: M
  refM2: M
}

type O {
  id: ID
  refN: N
  refK: K
}

type P {
  id: ID
  refN: N
  refO: O
}
